### ISSUE TITLE
Number classes in JUMP-CP

### ISSUE THREAD

**Issue by chaudatascience** [insitro/ChannelViT#5]
In the paper, it mentions that JUM-CP contains 160 classes, but in the scripts, `num_classes` is set to 161.

```
    python channelvit/main/main_supervised.py \
    ...
    meta_arch.num_classes=161\
  ```

I was wondering about the reason behind this difference.
Could you please clarify it?

Thank you!
Best,
Chau

**Comment by srinivasans-insitro** [comment]
@chaudatascience Sorry for the confusion. The JUMP-CP dataset contains 160 perturbations and 1 control treatment. So, we use `num_classes=161` to classify between all conditions (perturbations and controls)

**Comment by chaudatascience** [comment]
Thank you for the clarification!
