### ISSUE TITLE
Sharing the weights

### ISSUE THREAD

**Issue by iacopo97** [insitro/ChannelViT#6]
Thank you for your extraordinary work, Are you planning to share the weights of your models?

**Comment by srinivasans-insitro** [comment]
@iacopo97 Thank you for reaching out. We've now shared the pre-trained weights of our models. You can load them using torch hub as described here: https://github.com/insitro/ChannelViT?tab=readme-ov-file#pretrained-models-on-pytorch-hub.

**Comment by iacopo97** [comment]
Thank you very much
